ARG ALPINE_VER=3.15
ARG BWA_VER=0.7.17
ARG SAM_VER=1.9
ARG BED_VER=2.27.1
##########################################
FROM alpine:${ALPINE_VER} AS builder

ARG BWA_VER
ARG SAM_VER
ARG BED_VER
ARG PICARD_VER

RUN apk add --no-cache \
	autoconf \
	automake \
	cmake \
	gcc \
	g++ \
	git \
	zlib-dev \
	bzip2-dev \
	libc-dev \
	libtool \
	make \
	musl \
	python2 \
	tini \
	wget \
	xz-dev \
	ncurses-dev

RUN cd /; git clone --depth 1 https://github.com/microsoft/mimalloc; cd mimalloc; mkdir build; cd build; cmake ..; make -j$(nproc); make install

RUN git clone https://github.com/mjohnsonngi/bwa.git \
	&& cd bwa \
	&& make

RUN wget -q -P /tmp https://github.com/samtools/samtools/releases/download/${SAM_VER}/samtools-${SAM_VER}.tar.bz2 \
  && tar xjvf /tmp/samtools-${SAM_VER}.tar.bz2 -C /tmp \
  && cd /tmp/samtools-${SAM_VER}/ \
  && ./configure --without-curses \
  && make

RUN wget -q -P /tmp https://github.com/arq5x/bedtools2/releases/download/v${BED_VER}/bedtools-${BED_VER}.tar.gz \
  && tar xzvf /tmp/bedtools-${BED_VER}.tar.gz -C /tmp \
  && cd /tmp/bedtools${BED_VER%%.*}/ \
  && make

FROM rhub/r-minimal:alpine315-4.1-patched AS executor

RUN apk add --no-cache \
	zlib-dev \
	libstdc++ \
	libc6-compat \
	libgomp \
  openjdk8-jre \
	python2 \
  bash \
	rsync \
	&& mv /usr/lib/jvm/java-1.8-openjdk/jre/lib/amd64/jli/libjli.so /lib \
	&& cp /lib64/ld-linux-x86-64.so.2 /lib

RUN installr -d -t gfortran ggplot2

ARG BWA_VER
ARG SAM_VER
ARG BED_VER

COPY --from=builder /bwa/bwa /usr/local/bin/
COPY --from=builder /tmp/samtools-${SAM_VER}/samtools /usr/local/bin/
COPY --from=builder /tmp/bedtools*/bin/bedtools /usr/local/bin/
COPY --from=builder /usr/lib/liblzma.so.5 /usr/lib/liblzma.so.5
COPY --from=builder /mimalloc/build/*.so.* /lib
ENV LD_PRELOAD=/lib/libmimalloc.so
ENV MIMALLOC_LARGE_OS_PAGES=1

COPY ./scripts/* /scripts/

CMD ["/bin/bash"]
